"""initial schema

Revision ID: 33b3bad2f47e
Revises: 
Create Date: 2026-07-25 00:58:11.392317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3bad2f47e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debate_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('judge_winner', sa.String(length=20), nullable=False),
    sa.Column('user_agrees', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debate_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debate_votes_id'), ['id'], unique=False)

    op.create_table('free_key_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('free_key_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_key_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_key_claims_key_fingerprint'), ['key_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_key_claims_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('research_depth', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('encryption_key', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key', sa.Text(), nullable=True),
    sa.Column('openai_api_key', sa.Text(), nullable=True),
    sa.Column('tavily_api_key', sa.Text(), nullable=True),
    sa.Column('voyage_api_key', sa.Text(), nullable=True),
    sa.Column('google_api_key', sa.Text(), nullable=True),
    sa.Column('mistral_api_key', sa.Text(), nullable=True),
    sa.Column('groq_api_key', sa.Text(), nullable=True),
    sa.Column('nvidia_api_key', sa.Text(), nullable=True),
    sa.Column('deepseek_api_key', sa.Text(), nullable=True),
    sa.Column('preferred_provider', sa.String(length=50), nullable=True),
    sa.Column('pinecone_api_key_enc', sa.Text(), nullable=True),
    sa.Column('pinecone_environment', sa.String(), nullable=True),
    sa.Column('pinecone_index_name', sa.String(), nullable=True),
    sa.Column('neo4j_uri', sa.String(), nullable=True),
    sa.Column('neo4j_user', sa.String(), nullable=True),
    sa.Column('neo4j_password_enc', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('notifications', sa.JSON(), nullable=True),
    sa.Column('integrations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('user_preferences')
    with op.batch_alter_table('free_key_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_key_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_free_key_claims_key_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_free_key_claims_id'))

    op.drop_table('free_key_claims')
    with op.batch_alter_table('debate_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debate_votes_id'))

    op.drop_table('debate_votes')
    # ### end Alembic commands ###
