"""add usage_logs

Revision ID: 683d3822caae
Revises: ffc9c4d2059c
Create Date: 2026-07-25 19:09:37.318611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683d3822caae'
down_revision: Union[str, Sequence[str], None] = 'ffc9c4d2059c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_logs_user_mode', ['user_id', 'mode'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_logs_user_mode')
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_created_at'))

    op.drop_table('usage_logs')
    # ### end Alembic commands ###
