"""add research_cache

Revision ID: ffc9c4d2059c
Revises: 33b3bad2f47e
Create Date: 2026-07-25 01:27:00.677652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc9c4d2059c'
down_revision: Union[str, Sequence[str], None] = '33b3bad2f47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_cache_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_cache_id'), ['id'], unique=False)
        batch_op.create_index('ix_research_cache_lookup', ['user_id', 'query_hash', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_cache_query_hash'), ['query_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_cache_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_cache_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_cache_query_hash'))
        batch_op.drop_index('ix_research_cache_lookup')
        batch_op.drop_index(batch_op.f('ix_research_cache_id'))
        batch_op.drop_index(batch_op.f('ix_research_cache_created_at'))

    op.drop_table('research_cache')
    # ### end Alembic commands ###
